/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectE;

/**
 *
 * @author Endra
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;





public class BarangForm extends javax.swing.JFrame {
    private Connection conn = null;
    private DefaultTableModel tableModel;

    /**
     * Creates new form BarangForm
     */
    public BarangForm() {
        initComponents();
        conn = DatabaseConnection.connect();
        loadTable();
    }
    
 
    
    
      private void loadTable() {
        String query = "SELECT * FROM barang";
        tableModel = new DefaultTableModel();
        tableModel.addColumn("ID");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Harga");
        tableModel.addColumn("Stok");
        tableModel.addColumn("Tanggal Masuk");
        
        
     try {
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                tableModel.addRow(new Object[]{
                    rs.getInt("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getInt("harga_barang"),
                    rs.getInt("stock_barang"),
                    rs.getTimestamp("tanggal_masuk")
                });
            }
            TableBarang.setModel(tableModel);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtNamaBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtStock = new javax.swing.JTextField();
        TambahBtn = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JToggleButton();
        BtnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setText("id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 40, -1));

        txtIdBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBarangActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 40, 30));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel1.setText("Nama Barang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 84, -1));

        TxtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaBarangActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 300, 38));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel2.setText("harga");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 40, -1));
        jPanel1.add(TxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 300, 57));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setText("Stock");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 40, -1));
        jPanel1.add(TxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 300, 64));

        TambahBtn.setBackground(new java.awt.Color(51, 204, 0));
        TambahBtn.setText("Tambah");
        TambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahBtnActionPerformed(evt);
            }
        });
        jPanel1.add(TambahBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 423, -1, 30));

        BtnUpdate.setBackground(new java.awt.Color(255, 255, 0));
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 111, 30));

        BtnHapus.setBackground(new java.awt.Color(204, 0, 51));
        BtnHapus.setForeground(new java.awt.Color(255, 255, 255));
        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, 30));

        btnKembali.setBackground(java.awt.Color.lightGray);
        btnKembali.setText("x");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        TableBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_barang", "Nama_barang", "harga_Barang", "Stock", "Tanggal_Masuk"
            }
        ));
        jScrollPane1.setViewportView(TableBarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 640, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 760, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
         int jawaban = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin kembali ke Menu Utama?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
         
             if (jawaban == JOptionPane.YES_OPTION) {
            MainForm mainForm = new MainForm();
            mainForm.setVisible(true);
            this.dispose(); // Menutup frame BarangForm saat ini
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtIdBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBarangActionPerformed
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_txtIdBarangActionPerformed

    private void TambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBtnActionPerformed
       String namaBarang = TxtNamaBarang.getText();
        int hargaBarang = Integer.parseInt(TxtHarga.getText());
        int stockBarang = Integer.parseInt(TxtStock.getText());


        String query = "INSERT INTO barang (nama_barang, harga_barang, stock_barang) VALUES (?, ?, ?)";

        
            try {
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, namaBarang);
            pst.setInt(2, hargaBarang);
            pst.setInt(3, stockBarang);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");
            loadTable();
            TxtNamaBarang.setText("");
            txtIdBarang.setText("");
            TxtHarga.setText("");
            TxtStock.setText("");
            
        } catch (SQLException e) {
            e.printStackTrace();
        }  
        
        
        
    }//GEN-LAST:event_TambahBtnActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        
         int selectedRow = TableBarang.getSelectedRow();
          if (selectedRow != -1) {
            int idBarang = (int) tableModel.getValueAt(selectedRow, 0);
            String namaBarang = TxtNamaBarang.getText();
            int hargaBarang = Integer.parseInt(TxtHarga.getText());
            int stockBarang = Integer.parseInt(TxtStock.getText());
            
            String query = "UPDATE barang SET nama_barang = ?, harga_barang = ?, stock_barang = ? WHERE id_barang = ?";
            
            
             try {
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setString(1, namaBarang);
                pst.setInt(2, hargaBarang);
                pst.setInt(3, stockBarang);
                pst.setInt(4, idBarang);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
                loadTable();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diupdate");
            
            
          }
         
       
         
        
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void TxtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaBarangActionPerformed
        // TODO add your handling code here:
    
    
    }//GEN-LAST:event_TxtNamaBarangActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = TableBarang.getSelectedRow();
            if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus!");
            return;
        }
            int idBarang = (int) tableModel.getValueAt(selectedRowIndex, 0);
            String query = "DELETE FROM barang WHERE id_barang = ?";
            
        try {
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setInt(1, idBarang);
        
        int deletedRows = pst.executeUpdate();
        
        if (deletedRows > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            loadTable(); // Reload table setelah hapus
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data!");
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_BtnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JToggleButton BtnUpdate;
    private javax.swing.JTable TableBarang;
    private javax.swing.JButton TambahBtn;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtNamaBarang;
    private javax.swing.JTextField TxtStock;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdBarang;
    // End of variables declaration//GEN-END:variables
}
