/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectE;

import javax.swing.JOptionPane;

/**
 *
 * @author Endra
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAboutUs1 = new javax.swing.JButton();
        BtnTransaksi = new javax.swing.JButton();
        btnDataMaster = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnLaporan1 = new javax.swing.JButton();
        BtnLogut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAboutUs1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnAboutUs1.setText("About");
        BtnAboutUs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAboutUs1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAboutUs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 240, 80));

        BtnTransaksi.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BtnTransaksi.setText("Transaksi");
        BtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 240, 90));

        btnDataMaster.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDataMaster.setText("Data Barang");
        btnDataMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataMasterActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 240, 80));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectE/Gambar/6.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 360, 460));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat Datang, Admin! ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 436, 230, 67));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 480, 610));

        BtnLaporan1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnLaporan1.setText("Laporan");
        BtnLaporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaporan1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLaporan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 240, 80));

        BtnLogut.setBackground(new java.awt.Color(204, 0, 0));
        BtnLogut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnLogut.setText("Log Out");
        BtnLogut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogutActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 240, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataMasterActionPerformed
        // TODO add your handling code here:
        BarangForm barangForm = new BarangForm(); 
        barangForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDataMasterActionPerformed

    private void BtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransaksiActionPerformed
        // TODO add your handling code here:
    TransaksiForm transaksiForm = new TransaksiForm();
    transaksiForm.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_BtnTransaksiActionPerformed

    private void BtnAboutUs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAboutUs1ActionPerformed
        // TODO add your handling code here:
        AboutUsForm aboutUsForm = new AboutUsForm();
        aboutUsForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAboutUs1ActionPerformed

    private void BtnLaporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaporan1ActionPerformed
        // TODO add your handling code here:
        LaporanForm lf = new LaporanForm();
        lf.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnLaporan1ActionPerformed

    private void BtnLogutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogutActionPerformed
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    // Periksa respon dari pengguna
        if (response == JOptionPane.YES_OPTION) {
        // Tutup MainForm dan buka LoginForm
        this.dispose();
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }
    }//GEN-LAST:event_BtnLogutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAboutUs1;
    private javax.swing.JButton BtnLaporan1;
    private javax.swing.JButton BtnLogut;
    private javax.swing.JButton BtnTransaksi;
    private javax.swing.JButton btnDataMaster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
